require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DawsController do

  # This should return the minimal set of attributes required to create a valid
  # Daw. As you add validations to Daw, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DawsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all daws as @daws" do
      daw = Daw.create! valid_attributes
      get :index, {}, valid_session
      assigns(:daws).should eq([daw])
    end
  end

  describe "GET show" do
    it "assigns the requested daw as @daw" do
      daw = Daw.create! valid_attributes
      get :show, {:id => daw.to_param}, valid_session
      assigns(:daw).should eq(daw)
    end
  end

  describe "GET new" do
    it "assigns a new daw as @daw" do
      get :new, {}, valid_session
      assigns(:daw).should be_a_new(Daw)
    end
  end

  describe "GET edit" do
    it "assigns the requested daw as @daw" do
      daw = Daw.create! valid_attributes
      get :edit, {:id => daw.to_param}, valid_session
      assigns(:daw).should eq(daw)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Daw" do
        expect {
          post :create, {:daw => valid_attributes}, valid_session
        }.to change(Daw, :count).by(1)
      end

      it "assigns a newly created daw as @daw" do
        post :create, {:daw => valid_attributes}, valid_session
        assigns(:daw).should be_a(Daw)
        assigns(:daw).should be_persisted
      end

      it "redirects to the created daw" do
        post :create, {:daw => valid_attributes}, valid_session
        response.should redirect_to(Daw.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved daw as @daw" do
        # Trigger the behavior that occurs when invalid params are submitted
        Daw.any_instance.stub(:save).and_return(false)
        post :create, {:daw => {  }}, valid_session
        assigns(:daw).should be_a_new(Daw)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Daw.any_instance.stub(:save).and_return(false)
        post :create, {:daw => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested daw" do
        daw = Daw.create! valid_attributes
        # Assuming there are no other daws in the database, this
        # specifies that the Daw created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Daw.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => daw.to_param, :daw => { "these" => "params" }}, valid_session
      end

      it "assigns the requested daw as @daw" do
        daw = Daw.create! valid_attributes
        put :update, {:id => daw.to_param, :daw => valid_attributes}, valid_session
        assigns(:daw).should eq(daw)
      end

      it "redirects to the daw" do
        daw = Daw.create! valid_attributes
        put :update, {:id => daw.to_param, :daw => valid_attributes}, valid_session
        response.should redirect_to(daw)
      end
    end

    describe "with invalid params" do
      it "assigns the daw as @daw" do
        daw = Daw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Daw.any_instance.stub(:save).and_return(false)
        put :update, {:id => daw.to_param, :daw => {  }}, valid_session
        assigns(:daw).should eq(daw)
      end

      it "re-renders the 'edit' template" do
        daw = Daw.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Daw.any_instance.stub(:save).and_return(false)
        put :update, {:id => daw.to_param, :daw => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested daw" do
      daw = Daw.create! valid_attributes
      expect {
        delete :destroy, {:id => daw.to_param}, valid_session
      }.to change(Daw, :count).by(-1)
    end

    it "redirects to the daws list" do
      daw = Daw.create! valid_attributes
      delete :destroy, {:id => daw.to_param}, valid_session
      response.should redirect_to(daws_url)
    end
  end

end
